name: Deploy to cPanel Hosting (finance.cone.rw)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0
        with:
          server: ftp.cone.rw
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
<<<<<<< HEAD
          passive: true
=======
>>>>>>> 1d1e9456a1e055133490e528e529f4205bc25e19
          local-dir: ./
          server-dir: /public_html/finance.cone.rw/